#!/bin/sh
# Entrypoint script for Graphiti MCP Server
# Maps MADEINOZ_KNOWLEDGE_* prefixed variables to unprefixed container variables
# This keeps .env clean while providing what the container expects

set -e

# Map prefixed variables to unprefixed container variables
# Only set if the prefixed version exists (non-empty)
test -n "$MADEINOZ_KNOWLEDGE_MODEL_NAME" && export MODEL_NAME="$MADEINOZ_KNOWLEDGE_MODEL_NAME"
test -n "$MADEINOZ_KNOWLEDGE_LLM_PROVIDER" && export LLM_PROVIDER="$MADEINOZ_KNOWLEDGE_LLM_PROVIDER"
test -n "$MADEINOZ_KNOWLEDGE_EMBEDDER_PROVIDER" && export EMBEDDER_PROVIDER="$MADEINOZ_KNOWLEDGE_EMBEDDER_PROVIDER"
test -n "$MADEINOZ_KNOWLEDGE_EMBEDDER_MODEL" && export EMBEDDER_MODEL="$MADEINOZ_KNOWLEDGE_EMBEDDER_MODEL"
test -n "$MADEINOZ_KNOWLEDGE_OPENAI_API_KEY" && export OPENAI_API_KEY="$MADEINOZ_KNOWLEDGE_OPENAI_API_KEY"
test -n "$MADEINOZ_KNOWLEDGE_OPENAI_BASE_URL" && export OPENAI_BASE_URL="$MADEINOZ_KNOWLEDGE_OPENAI_BASE_URL"
test -n "$MADEINOZ_KNOWLEDGE_OLLAMA_BASE_URL" && export OLLAMA_BASE_URL="$MADEINOZ_KNOWLEDGE_OLLAMA_BASE_URL"
test -n "$MADEINOZ_KNOWLEDGE_ANTHROPIC_API_KEY" && export ANTHROPIC_API_KEY="$MADEINOZ_KNOWLEDGE_ANTHROPIC_API_KEY"
test -n "$MADEINOZ_KNOWLEDGE_GOOGLE_API_KEY" && export GOOGLE_API_KEY="$MADEINOZ_KNOWLEDGE_GOOGLE_API_KEY"
test -n "$MADEINOZ_KNOWLEDGE_GROQ_API_KEY" && export GROQ_API_KEY="$MADEINOZ_KNOWLEDGE_GROQ_API_KEY"
test -n "$MADEINOZ_KNOWLEDGE_VOYAGE_API_KEY" && export VOYAGE_API_KEY="$MADEINOZ_KNOWLEDGE_VOYAGE_API_KEY"

# Execute the main container command
exec "$@"
