# Podman Compose configuration for Madeinoz Knowledge System (Neo4j - default)
#
# This is a symlink/alias to podman-compose-neo4j.yml for convenience.
# Neo4j is the recommended default backend.
#
# For FalkorDB backend, use: podman-compose-falkordb.yml
#
# To use a specific backend, run:
#   podman-compose -f src/server/podman-compose-neo4j.yml up -d
#   podman-compose -f src/server/podman-compose-falkordb.yml up -d

name: madeinoz-knowledge-system

networks:
  madeinoz-knowledge-net:
    external: true

volumes:
  madeinoz-knowledge-neo4j-data:
    external: true
  madeinoz-knowledge-neo4j-logs:
    external: true

services:
  neo4j:
    image: neo4j:latest
    container_name: madeinoz-knowledge-neo4j
    restart: unless-stopped
    networks:
      - madeinoz-knowledge-net
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - madeinoz-knowledge-neo4j-data:/data
      - madeinoz-knowledge-neo4j-logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/madeinozknowledge
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_memory_pagecache_size=512m
      - NEO4J_dbms_usage__report_enabled=false
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  graphiti-mcp:
    image: ghcr.io/madeinoz67/madeinoz-knowledge-system:latest
    container_name: madeinoz-knowledge-graph-mcp
    restart: unless-stopped
    networks:
      - madeinoz-knowledge-net
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=madeinozknowledge
      - NEO4J_DATABASE=neo4j
      - GRAPHITI_GROUP_ID=main
      - SEMAPHORE_LIMIT=10
      - CONFIG_PATH=/app/mcp/config/config.yaml
      - GRAPHITI_TELEMETRY_ENABLED=false
      - MADEINOZ_KNOWLEDGE_SEARCH_ALL_GROUPS=true
    volumes:
      - ./config-neo4j.yaml:/app/mcp/config/config.yaml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    env_file:
      - /tmp/madeinoz-knowledge-mcp.env
    depends_on:
      neo4j:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sf", "--max-time", "5", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["uv", "run", "main.py"]
