# Podman Compose configuration for Madeinoz Knowledge System with Neo4j backend
# Uses a shared public network for both services

name: madeinoz-knowledge-system
#
# Services:
#   - neo4j: Graph database backend (Cypher queries, no RediSearch/Lucene escaping needed)
#   - graphiti-mcp: MCP server (exposed to host)
#
# Madeinoz Patches APPLIED:
#   1. entrypoint.sh - Selects appropriate config based on DATABASE_TYPE
#   2. graphiti_mcp_server.py - Enables searching across ALL groups when no
#      group_ids are specified. This ensures knowledge stored in different
#      groups (e.g., osint-profiles, main) is discoverable.
#   3. factories.py - Enables Ollama/custom endpoint support by using
#      OpenAIGenericClient (which uses /v1/chat/completions) instead of
#      OpenAIClient (which uses /v1/responses that Ollama doesn't support).
#      This fixes upstream GitHub issue #1116.
#   4. falkordb_lucene.py - Lucene query sanitization for FalkorDB backend.
#      Fixes RediSearch syntax errors with special characters in group_ids
#      and episode content. Addresses Graphiti issues #815, #1118.
#
# Usage from pack directory:
#   1. Copy config/.env.example to ~/.claude/.env and configure your API keys
#   2. Set MADEINOZ_KNOWLEDGE_DATABASE_TYPE=neo4j in your .env
#   3. Run: bun run src/server/start.sh (handles .env generation automatically)
#   4. MCP server uses HTTP transport at: http://localhost:8000/mcp
#   5. Access Neo4j Browser at: http://localhost:7474

networks:
  madeinoz-knowledge-net:
    external: true  # Use existing public network created by install script

volumes:
  madeinoz-knowledge-neo4j-data:
    external: true  # Use existing volume with persisted data
  madeinoz-knowledge-neo4j-logs:
    external: true  # Use existing volume with persisted logs

services:
  # Neo4j Graph Database
  # Native graph database with Cypher query language
  neo4j:
    image: neo4j:latest
    container_name: madeinoz-knowledge-neo4j
    restart: unless-stopped
    networks:
      - madeinoz-knowledge-net
    ports:
      - "7474:7474"  # Neo4j Browser HTTP
      - "7687:7687"  # Bolt protocol
    volumes:
      - madeinoz-knowledge-neo4j-data:/data
      - madeinoz-knowledge-neo4j-logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/madeinozknowledge
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_memory_pagecache_size=512m
      - NEO4J_dbms_usage__report_enabled=false
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Graphiti MCP Server (Neo4j backend)
  # Uses zepai/knowledge-graph-mcp:standalone image for Neo4j support
  # Environment variables provided via env_file generated by start.sh
  graphiti-mcp:
    image: zepai/knowledge-graph-mcp:standalone
    container_name: madeinoz-knowledge-graph-mcp
    restart: unless-stopped
    networks:
      - madeinoz-knowledge-net
    ports:
      - "8000:8000"  # MCP HTTP endpoint
    volumes:
      # Config files for database selection
      - ./config-neo4j.yaml:/tmp/config-neo4j.yaml:ro
      - ./config-falkordb.yaml:/tmp/config-falkordb.yaml:ro
      # Madeinoz Patch: Entrypoint - Selects config based on DATABASE_TYPE
      - ./entrypoint.sh:/entrypoint.sh:ro
      # Madeinoz Patch: Search ALL groups by default when no group_ids specified
      - ./patches/graphiti_mcp_server.py:/app/mcp/src/graphiti_mcp_server.py:ro
      # Madeinoz Patch: Ollama/custom endpoint support (fixes GitHub issue #1116)
      - ./patches/factories.py:/app/mcp/src/services/factories.py:ro
      # Madeinoz Patch: FalkorDB Lucene sanitization (fixes #815, #1118)
      - ./patches/falkordb_lucene.py:/app/mcp/patches/falkordb_lucene.py:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    env_file:
      # Generated by start.sh from MADEINOZ_KNOWLEDGE_* prefixed variables
      - /tmp/madeinoz-knowledge-mcp.env
    depends_on:
      neo4j:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sf", "--max-time", "5", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["uv", "run", "main.py"]
