# Podman Compose configuration for Madeinoz Knowledge System with FalkorDB backend
# Uses a shared public network for both services

name: madeinoz-knowledge-system
#
# Services:
#   - falkordb: Redis-based graph database
#   - graphiti-mcp: MCP server (exposed to host)
#
# Madeinoz Patches APPLIED:
#   1. entrypoint.sh - Selects appropriate config based on DATABASE_TYPE
#
# Usage from pack directory:
#   1. Copy config/.env.example to ~/.claude/.env and configure your API keys
#   2. Run: bun run src/server/start.sh (handles .env generation automatically)
#   3. MCP server uses HTTP transport at: http://localhost:8000/mcp
#   4. Access FalkorDB web UI at: http://localhost:3000

networks:
  madeinoz-knowledge-net:
    external: true  # Use existing public network created by install script

volumes:
  madeinoz-knowledge-falkordb-data:
    external: true  # Use existing volume with persisted data

services:
  # FalkorDB Graph Database
  # Redis-based graph database
  falkordb:
    image: falkordb/falkordb:latest
    container_name: madeinoz-knowledge-falkordb
    restart: unless-stopped
    networks:
      - madeinoz-knowledge-net
    ports:
      - "3000:3000"  # FalkorDB web UI
    volumes:
      - madeinoz-knowledge-falkordb-data:/data
    environment:
      - FALKORDB_PASSWORD=
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Graphiti MCP Server (FalkorDB backend)
  # Uses falkordb/graphiti-knowledge-graph-mcp:latest image
  # Environment variables provided via env_file generated by start.sh
  graphiti-mcp:
    image: ghcr.io/madeinoz67/madeinoz-knowledge-system:latest
    container_name: madeinoz-knowledge-graph-mcp
    restart: unless-stopped
    networks:
      - madeinoz-knowledge-net
    ports:
      - "8000:8000"  # MCP HTTP endpoint
    volumes:
      # Config files for database selection
      - ./config-neo4j.yaml:/tmp/config-neo4j.yaml:ro
      - ./config-falkordb.yaml:/tmp/config-falkordb.yaml:ro
      # Madeinoz Patch: Entrypoint - Selects config based on DATABASE_TYPE
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    env_file:
      # Generated by start.sh from MADEINOZ_KNOWLEDGE_* prefixed variables
      - /tmp/madeinoz-knowledge-mcp.env
    depends_on:
      falkordb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sf", "--max-time", "5", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
